INFO     conftest:conftest.py:51 Начало теста: tests/tests_api/test_api.py::test_user_login[user_credentials0]
INFO     conftest:conftest.py:55 Тест успешно пройден: tests/tests_api/test_api.py::test_user_login[user_credentials0]